spring.application.name=backendbank

spring.datasource.url=jdbc:postgresql://localhost:5432/backendbank
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
